use super::{CodeWriter, DagContext, Emitter, EmitOutput};
use crate::error::Result;

pub struct ReactEmitter;

impl Emitter for ReactEmitter {
    fn emit(&self, ctx: &DagContext<'_>) -> Result<EmitOutput> {
        let mut output = Vec::new();

        // Generate one .tsx file per node
        for (name, vt) in &ctx.nodes {
            let tsx = emit_node_tsx(name, vt, ctx)?;
            output.push((format!("{}.tsx", name), tsx));
        }

        // Generate index.tsx (orchestrator)
        let index = emit_index_tsx(ctx)?;
        output.push(("index.tsx".to_string(), index));

        // Generate types.ts
        let types = emit_types_ts();
        output.push(("types.ts".to_string(), types));

        Ok(output)
    }
}

fn emit_node_tsx(name: &str, vt: &crate::ast::VtFile, _ctx: &DagContext<'_>) -> Result<String> {
    let mut w = CodeWriter::new(512);

    w.line("// Auto-generated by venturi emit --format react");
    w.line(&format!("// Node: {} [{:?}]", name, vt.kind));
    w.blank();

    // Input interface
    let input_name = format!("{}Inputs", capitalize(name));
    w.line(&format!("export interface {} {{", input_name));
    w.indent();
    if vt.inputs.is_empty() {
        w.line("// no inputs");
    } else {
        for input in &vt.inputs {
            let ts_type = vt_type_to_ts(&input.ty);
            w.line(&format!("  {}: {};", input.name, ts_type));
        }
    }
    w.dedent();
    w.line("}");
    w.blank();

    // Output interface
    let output_name = format!("{}Outputs", capitalize(name));
    w.line(&format!("export interface {} {{", output_name));
    w.indent();
    if vt.outputs.is_empty() {
        w.line("// no outputs");
    } else {
        for output in &vt.outputs {
            let ts_type = vt_type_to_ts(&output.ty);
            w.line(&format!("  {}: {};", output.name, ts_type));
        }
    }
    w.dedent();
    w.line("}");
    w.blank();

    // Function signature and body
    let func_name = vt
        .func
        .as_ref()
        .map(|f| f.name.as_str())
        .unwrap_or("render");
    w.line(&format!(
        "export function {}(_inputs: {}): {} {{",
        func_name, input_name, output_name
    ));
    w.indent();

    if let Some(func) = &vt.func {
        for stmt in &func.body {
            emit_stmt(&mut w, stmt);
        }
    }

    // Default return if none exists
    if vt.outputs.len() == 1 {
        let out_name = &vt.outputs[0].name;
        w.line(&format!("return {{ {}: undefined }};", out_name));
    } else if !vt.outputs.is_empty() {
        let defaults = vt
            .outputs
            .iter()
            .map(|o| format!("{}: undefined", o.name))
            .collect::<Vec<_>>()
            .join(", ");
        w.line(&format!("return {{ {} }};", defaults));
    }

    w.dedent();
    w.line("}");

    Ok(w.into_string())
}

fn emit_index_tsx(ctx: &DagContext<'_>) -> Result<String> {
    let mut w = CodeWriter::new(ctx.nodes.len() * 256);

    w.line("// Auto-generated by venturi emit --format react");
    w.line("// Orchestrator: wires all nodes together");
    w.blank();

    // Imports
    for (name, _) in &ctx.nodes {
        let camel = capitalize(name);
        w.line(&format!("import {{ render as {}Render }} from \"./{}\";", camel, name));
    }
    w.blank();

    w.line("export function runDag() {");
    w.indent();

    // Calls in topological order
    for (name, _) in &ctx.nodes {
        let camel = capitalize(name);
        let deps = ctx.deps_of(name);

        if deps.is_empty() {
            w.line(&format!("const {} = {}Render({{}});", name, camel));
        } else {
            // Collect deps as props
            let props = deps
                .iter()
                .map(|dep| {
                    let dep_camel = capitalize(dep);
                    format!("{}: {}.output", dep, dep)
                })
                .collect::<Vec<_>>()
                .join(", ");
            w.line(&format!("const {} = {}Render({{{}}});", name, camel, props));
        }
    }

    w.blank();
    let ret = ctx
        .nodes
        .iter()
        .map(|(n, _)| format!("{}: {}", n, n))
        .collect::<Vec<_>>()
        .join(", ");
    w.line(&format!("return {{ {} }};", ret));

    w.dedent();
    w.line("}");

    Ok(w.into_string())
}

fn emit_types_ts() -> String {
    "// Auto-generated by venturi emit --format react\n\
     export type VtDataFrame = Record<string, unknown>[];\n\
     export type VtResult<T> = { ok: T } | { err: string };\n"
        .to_string()
}

fn vt_type_to_ts(ty: &crate::ast::VtType) -> &'static str {
    use crate::ast::VtType;
    match ty {
        VtType::Int | VtType::Float => "number",
        VtType::Bool => "boolean",
        VtType::Str => "string",
        VtType::DataFrame => "VtDataFrame",
        VtType::Custom(_) => "unknown",
    }
}

fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
    }
}

fn emit_stmt(w: &mut CodeWriter, stmt: &crate::ast::Stmt) {
    use crate::ast::Stmt;
    match stmt {
        Stmt::Assign(name, expr) => {
            let e = emit_expr(expr);
            w.line(&format!("const {} = {};", name, e));
        }
        Stmt::Return(expr) => {
            let e = emit_expr(expr);
            w.line(&format!("return {};", e));
        }
        Stmt::Expr(expr) => {
            let e = emit_expr(expr);
            w.line(&format!("{};", e));
        }
        Stmt::TryCatch { body, catches } => {
            w.line("try {");
            w.indent();
            for s in body {
                emit_stmt(w, s);
            }
            w.dedent();
            for catch in catches {
                w.line(&format!("}} catch ({}_{}: unknown) {{", catch.error_type, catch.binding));
                w.indent();
                for s in &catch.body {
                    emit_stmt(w, s);
                }
                w.dedent();
            }
            w.line("}");
        }
    }
}

fn emit_expr(expr: &crate::ast::Expr) -> String {
    use crate::ast::Expr;
    match expr {
        Expr::Ident(s) => s.clone(),
        Expr::IntLit(n) => n.to_string(),
        Expr::FloatLit(f) => f.to_string(),
        Expr::StrLit(s) => format!("{:?}", s),
        Expr::BoolLit(b) => b.to_string(),
        Expr::Call(name, args) => {
            let args_strs: Vec<String> = args.iter().map(emit_expr).collect();
            let joined = args_strs.join(", ");
            if name == "log" {
                format!("console.log({})", joined)
            } else {
                format!("{}({})", name, joined)
            }
        }
        Expr::FieldAccess(obj, field) => {
            format!("{}.{}", emit_expr(obj), field)
        }
        Expr::ResultOk(inner) => {
            format!("{{ ok: {} }}", emit_expr(inner))
        }
        Expr::ResultErr(inner) => {
            format!("{{ err: {} }}", emit_expr(inner))
        }
    }
}
